version: '3'

services:

  medicalweb:
    container_name: medicalweb
    image: medicalwebimage
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      #- ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Shanghai
    restart: always

  medicalproxy:
    container_name: medicalproxy
    image: nginx    
    ports:
      - "8500:8500"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - medicalweb
